# -*- coding: utf-8 -*-
"""K_Means_Clustering_Tutorial.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qQg6YIwe8OZouOXOnCXSBMLlX8-O6YEH

# Tutorial K-Means Clustering: Segmentasi Pelanggan Mall

## Tujuan
Melakukan segmentasi pelanggan mall menggunakan **K-Means Clustering** berdasarkan:
- **Annual Income (k$)**
- **Spending Score (1-100)**

**Dataset source:** [Mall_Customers.csv](https://gist.github.com/pravalliyaram/5c05f43d2351249927b8a3f3cc3e5ecf)
"""

# 1. Import library dan load data
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans

url = 'https://gist.github.com/pravalliyaram/5c05f43d2351249927b8a3f3cc3e5ecf/raw/8bd6144a87988213693754baaa13fb204933282d/Mall_Customers.csv'
data = pd.read_csv(url)

print('Dataset shape:', data.shape)
print(data.head())

"""## Step 1: Pemilihan Fitur

Kita hanya memakai 2 fitur agar mudah divisualisasikan dan fokus pada pola belanja pelanggan.

"""

# 2. Pilih fitur yang jalankan Elbow Method
features = data[['Annual Income (k$)', 'Spending Score (1-100)']]
print(features.describe())

# Elbow Method
wcss = []
for i in range(1, 11):
    kmeans = KMeans(n_clusters=i, random_state=42)
    kmeans.fit(features)
    wcss.append(kmeans.inertia_)

plt.figure(figsize=(9, 5))
plt.plot(range(1, 11), wcss, marker='o')
plt.xlabel('Jumlah Cluster (k)')
plt.ylabel('WCSS')
plt.title('Elbow Method')
plt.grid(True, alpha=0.3)
plt.xticks(range(1, 11))
plt.axvline(x=5, color='red', linestyle='--', label='Elbow Point (k=5)')
plt.legend()
plt.show()

"""## Step 2: Implementasi K-Means

Berdasarkan Elbow Method, jumlah cluster optimal adalah **5**.

"""

# 3. Jalankan K-Means dan visualisasi
kmeans = KMeans(n_clusters=5, random_state=42)
labels = kmeans.fit_predict(features)
data['Cluster'] = labels

print('Distribusi cluster:')
print(data['Cluster'].value_counts().sort_index())

# Visualisasi
plt.figure(figsize=(10, 7))
colors = ['red', 'blue', 'green', 'purple', 'orange']

for i in range(5):
    cluster_data = features[labels == i]
    plt.scatter(cluster_data['Annual Income (k$)'],
                cluster_data['Spending Score (1-100)'],
                s=60, alpha=0.7, c=colors[i], label=f'Cluster {i+1}')

centers = kmeans.cluster_centers_
plt.scatter(centers[:, 0], centers[:, 1], c='black', s=250, marker='X', label='Centroid')
plt.xlabel('Annual Income (k$)')
plt.ylabel('Spending Score (1-100)')
plt.title('Customer Segmentation dengan K-Means')
plt.legend()
plt.grid(True, alpha=0.3)
plt.show()

# 4. Analisis karakteristik setiap cluster
print("\n" + "="*80)
print("KARAKTERISTIK SETIAP CLUSTER")
print("="*80)

for cluster_id in range(5):
    cluster_data = data[data['Cluster'] == cluster_id]
    avg_income = cluster_data['Annual Income (k$)'].mean()
    avg_spending = cluster_data['Spending Score (1-100)'].mean()

    print(f"\nCLUSTER {cluster_id + 1} ({len(cluster_data)} pelanggan, {len(cluster_data)/len(data)*100:.1f}%)")
    print(f"  Rata-rata Income: ${avg_income:.2f}k  |  Rata-rata Spending Score: {avg_spending:.2f}")

    if avg_income > 80 and avg_spending > 50:
        segment = "💎 Premium (High Income, High Spending)"
    elif avg_income < 60 and avg_spending > 70:
        segment = "🛍️ Fashion-Conscious (Low Income, High Spending)"
    elif avg_income > 80 and avg_spending < 40:
        segment = "💰 Careful Spender (High Income, Low Spending)"
    elif avg_income < 60 and avg_spending < 40:
        segment = "📊 Budget-Conscious (Low Income, Low Spending)"
    else:
        segment = "⚖️ Middle Class (Medium Income, Medium Spending)"

    print(f"  Segmen: {segment}")

"""## Step 3: Interpretasi dan Aplikasi Bisnis

**5 Segmen Pelanggan:**

| Cluster | Segmen | Karakteristik | Strategi Marketing |
|---------|--------|---------------|-------------------|
| 1 | 💎 Premium | High Income, High Spending | Produk eksklusif, loyalty program |
| 2 | 🛍️ Fashion-Conscious | Low Income, High Spending | Tren fashion, cicilan, flash sales |
| 3 | 💰 Careful Spender | High Income, Low Spending | Value proposition, membership |
| 4 | 📊 Budget-Conscious | Low Income, Low Spending | Budget-friendly, promo hemat |
| 5 | ⚖️ Middle Class | Medium Income, Medium Spending | Mid-range products, balanced offers |

**Manfaat bisnis:**
- ✅ Personalisasi marketing per segmen
- ✅ Penentuan harga sesuai daya beli
- ✅ Strategi promosi yang lebih efektif
- ✅ Optimasi inventory berdasarkan preferensi segmen

"""